### ISSUE TITLE
Exporting Error: This network contains null or empty node name

### ISSUE THREAD

**Issue by sakura7621** [cytoscape/cytoscape-manual#51]
Hi,

I'm trying to export "WP2828 - Bladder Cancer - Homo sapiens" as a SIF file. 
However, I got an error ```This network contains null or empty node name.```. It exported an empty file.

How can I fix this issue?

Thank you!

**Comment by khanspers** [comment]
Hi @chaupmcs,
This is a known issue, and its due to how some information stored in the gpml model is handled in Cytoscape. It is reasonable that it should work for pathways imported as a network at least. I will add an issue to the [cytoscape-wikipathways-app](https://github.com/wikipathways/cytoscape-wikipathways-app/issues) repo.
